services:
  api:
    build: ./Farmers-Choice-API
    ports:
      - "3000:3000"
    volumes:
      - ./Farmers-Choice-API:/app
      - ./appData:/app/appData
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://db:27017/farmersdb
    depends_on:
      - db

  frontend:
    build: ./Farmers-Choice-FrontEnd
    ports:
      - "19006:19006"
    volumes:
      - ./Farmers-Choice-FrontEnd:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db