services:
  api:
    build: ./Farmers-Choice-API
    container_name: farmers-choice-api
    ports:
      - "3000:3000"
    volumes:
      - ./Farmers-Choice-API:/app:cached
      - ./appData:/app/appData:cached
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/farmers_choice
    depends_on:
      - mongo

  frontend:
    build: ./Farmers-Choice-FrontEnd
    container_name: farmers-choice-frontend
    ports:
      - "19006:19006"
    volumes:
      - ./Farmers-Choice-FrontEnd:/app:cached
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  mongo:
    image: mongo:6
    container_name: farmers-choice-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
