version: "3.9"
services:
  api:
    build: ./Farmers-Choice-API
    ports:
      - "3000:3000"
    volumes:
      - ./Farmers-Choice-API:/app
      - ./appData:/app/appData
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/farmers_choice
    depends_on:
      - mongo

  frontend:
    build: ./Farmers-Choice-FrontEnd
    ports:
      - "19006:19006"
    volumes:
      - ./Farmers-Choice-FrontEnd:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
