version: '3.8'
services:
  api:
    build: ./Farmers-Choice-API
    ports:
      - "3000:3000"
    volumes:
      - ./Farmers-Choice-API:/app
      - ./appData:/app/appData
    environment:
      - NODE_ENV=development
      - PORT=3000
      # Add other env vars as needed

  frontend:
    build: .
    ports:
      - "19006:19006"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api