// seedData/imageMap.js
const ImageMap = {
  Lettuce: '/assets/lettuce.jpeg',
  Capsicum: '/assets/Capsicum.jpeg',
  Carrots: '/assets/Carrots.jpeg',
  Egg: '/assets/Egg.jpeg',
  Love: '/assets/love.jpeg',
  Salad: '/assets/salad.jpeg',
  Spinach: '/assets/Spinach.jpeg',
  Peas: '/assets/Peas.jpeg',
  EggTrays: '/assets/eggTrays.jpeg',
  EggTray2: '/assets/eggTray2.jpeg',
  Eggs: '/assets/eggs.jpeg',
  Image1: '/assets/image1.jpeg',
  Farm: '/assets/farm.jpeg',
  Logo1: '/assets/Logo1.png',
  Bunny: '/assets/bunny.jpeg',
  Orange: '/assets/orange1.jpeg',
  Grapes: '/assets/grapes.jpeg',
  Sheep: '/assets/sheep.jpeg',
  JavaBanana: '/assets/Bluejavabananas.jpeg',
  Rabbit: '/assets/rabbit.jpeg',
  TomatoFarm: '/assets/tomatofarm.jpeg',
  Lemons: '/assets/lemons.jpeg',
  Apple: '/assets/apples.jpeg',
  Cows: '/assets/cows.jpeg',
  Bellpepper: '/assets/BellPepper.jpeg',
  Chinesecabbage: '/assets/chinesecabbage.jpeg',
  Grapess: '/assets/grapess.jpeg',
  Grapevariety: '/assets/grapevariety.jpeg',
  Bananas: '/assets/bananas.jpeg',
  Bananass: '/assets/bananass.jpeg',
  OrangeFarm: '/assets/orangefarm.jpeg',
  Oranges: '/assets/oranges.jpeg',
  Organiccarbagges: '/assets/OrganicCabbages.jpeg',
  Purplebananas: '/assets/purplebananas.jpeg',
  RedBanana: '/assets/RedBanana.jpeg',
  RedBananas: '/assets/RedBananas.jpeg',
  LacatanBananas: '/assets/LakatanBananas.jpeg',
  LeafyGreens: '/assets/LeafyGreens.jpeg',
  Groceries: '/assets/groceries.jpeg',
  Darkgrapes: '/assets/darkgrapes.jpeg'
};

export default ImageMap;