const ImageMap = {
  Lettuce: require('../assets/lettuce.jpeg'),
  Capsicum: require('../assets/Capsicum.jpeg'),
  Carrots: require('../assets/Carrots.jpeg'),
  Egg: require('../assets/Egg.jpeg'),
  Love: require('../assets/love.jpeg'),
  Salad: require('../assets/salad.jpeg'),
  Spinach: require('../assets/Spinach.jpeg'),
  Peas: require('../assets/Peas.jpeg'),
  EggTrays: require('../assets/eggTrays.jpeg'),
  EggTray2: require('../assets/eggTray2.jpeg'),
  Eggs: require('../assets/eggs.jpeg'),
  Image1: require('../assets/image1.jpeg'),
  Farm: require('../assets/farm.jpeg'),
  Logo1: require('../assets/Logo1.png'),
  Bunny: require('../assets/bunny.jpeg'),
  Orange: require('../assets/orange1.jpeg'),
  Grapes:require('../assets/grapes.jpeg'),
  Sheep: require('../assets/sheep.jpeg'),
  JavaBanana:require('../assets/Bluejavabananas.jpeg'),
  Rabbit:require('../assets/rabbit.jpeg'),
  TomatoFarm:require('../assets/tomatofarm.jpeg'),
  Lemons:require('../assets/lemons.jpeg'),
  Apple:require('../assets/apples.jpeg'),
  Cows:require('../assets/cows.jpeg'),
  Bellpepper:require('../assets/BellPepper.jpeg'),
  Chinesecabbage:require('../assets/chinesecabbage.jpeg'),
  Grapess:require('../assets/grapess.jpeg'),
  Grapevariety:require('../assets/grapevariety.jpeg'),
  Bananas:require('../assets/bananas.jpeg'),
  Bananass:require('../assets/bananass.jpeg'),
  OrangeFarm:require('../assets/orangefarm.jpeg'),
  Oranges:require('../assets/oranges.jpeg'),
  Organiccarbagges:require('../assets/OrganicCabbages.jpeg'),
  Purplebananas:require('../assets/purplebananas.jpeg'),
  RedBanana:require('../assets/RedBanana.jpeg'),
  RedBananas:require('../assets/RedBananas.jpeg'),
  LacatanBananas:require('../assets/LakatanBananas.jpeg'),
  LeafyGreens:require('../assets/LeafyGreens.jpeg'),
  Groceries:require('../assets/groceries.jpeg'),
  Darkgrapes:require('../assets/darkgrapes.jpeg'),
   
};

export default ImageMap;
